### ISSUE TITLE
Doens't work on build.phonegap.com

### ISSUE THREAD

**Issue by OhSoGood** [ddawson/Saved-Password-Editor#22]
Doesn't work on https://build.phonegap.com - they manage their form fields in a specific manner.

You may create a free account on their website to test it - it's fully free.

If you could fix this, that would be very much appreciated!
(and thank thank thank for this plugin)
Regards

**Comment by ddawson** [comment]
Hmm. This is an interesting case. I assume you're referring to logging in with an email and password; the other methods are third-party authentication, so those are out of scope. AFAICT, it actually does work, albeit not entirely perfectly. First of all, I find that the "Guess from current page" button works just fine. Second, the form may not be filled properly on a simple reload if you just typed in it. However, it seems to be just fine on subsequent visits, or if you perform a complete reload by holding the Shift key while clicking the reload button (or pressing Shift+Ctrl+R or Shift+Cmd+R).

In any case, the autofill behavior of Firefox, SeaMonkey, etc., has nothing to do with Saved Password Editor. If you just can't get your password saved for some reason, or you are experiencing some other *non-autofill* problem, I'll need details; please tell me:

* The application you're using--Firefox, SeaMonkey, or something else--and the version
* The version of SPE you're using
* A concise description of the problem
* What you expect to happen
* What actually happens

Otherwise, I will be closing this issue, and recommend you visit [Mozilla Support](https://support.mozilla.org/). Unless you're using SeaMonkey, in which case there is [a list of resources](http://www.seamonkey-project.org/community#support) on the SeaMonkey Project pages.

**Comment by ddawson** [comment]
No reply; closing.
