### ISSUE TITLE
Confirmation that this project has reached a dead end

### ISSUE THREAD

**Issue by LloydEwing** [ddawson/Saved-Password-Editor#32]
Daniel, I am confused.  Could you confirm that Saved Password Editor has reached a dead end as an add-on to Firefox on Windows?  I was recently forced to move from Win XP to Win 7, and so far I have not found a Firefox add-on with similar capabilities.  

After quite a bit of searching it seems to be apparent that Saved Password Editor is dead, but I can't find it explicitly stated anywhere.  The link 
https://addons.mozilla.org/addon/saved-password-editor/
doesn't work on your main page
https://github.com/ddawson/Saved-Password-Editor

I understand how changes in life sometimes force us to abandon valuable projects.  Also, I know the ultimate solution is Linux, but I am not yet ready to make that leap.

Thanks very much!

**Comment by ddawson** [comment]
It has nothing to do with operating systems, and everything to do with development of Firefox. As of version 57, it no longer supports "legacy" extensions, which is anything other than WebExtensions. The problem, where SPE—and any other similar extension—is concerned, is that we can now only do things that are enabled by appropriate APIs. There was a project that intended to add a logins API for WebExtensions. A [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1324919) was opened, and is still open. But for whatever reasons, development never went very far. As you can see if you look at it, nothing indicative of progress has been commented there since April 2017. At this point, I have no hope the API will ever materialize.

So, when it comes to Firefox, yes, this is at a dead end. But other applications are still served. Back in the day, I assumed there would be a WebExtensions API and forked development of SPE into [Classic Password Editor](https://addons.thunderbird.net/addon/classic-password-editor/), which was to continue the legacy code while SPE would be turned into a WebExtension, since there was an upgrade path. If I'd known things would turn out this way I wouldn't have bothered with such a complication. But, oh well. Last I checked, CPE is compatible with Thunderbird and a web browser called Pale Moon.

I've updated the project description to help avoid confusion in the future.
