### ISSUE TITLE
A bit of resurrection

### ISSUE THREAD

**Issue by 117649** [ddawson/Saved-Password-Editor#33]
Made a version of this that works on modern Firefox and Waterfox G3.
https://github.com/117649/SavedPasswordEditorRedux
![](https://user-images.githubusercontent.com/8281345/115109435-47a12f80-9fa8-11eb-808d-f2ba6bbc284e.png)

**Comment by ddawson** [comment]
Not bad. I definitely approve. But I hope you're aware that SPE is outdated compared to [Classic Password Editor](https://github.com/ddawson/Classic-Password-Editor). SPE is the one I wanted to turn into a WebExtension—until Mozilla killed that possibility—hence the fork.

**Comment by 117649** [comment]
> 
> 
> Not bad. I definitely approve. But I hope you're aware that SPE is outdated compared to [Classic Password Editor](https://github.com/ddawson/Classic-Password-Editor). SPE is the one I wanted to turn into a WebExtension—until Mozilla killed that possibility—hence the fork.

When I start doing this I really don't...

But anyway I just checked difference with CPE briefly nothing really hurts I think.
Most changes after split are for adapt to apps other then FF, in order to work on modern FF this repo have already gone through  changes at such places.

**Comment by dhdurgee** [comment]
Which version, if any, should be used with the current SeaMonkey?  I am running 2.53.15 and would like to use the appropriate version.  Am I correct that this should be used in conjunction with the "old password manager" that is accessed via:

[chrome://passwordmgr/content/passwordManager.xul](url)

Thank you for your assistance.

Dave

**Comment by ddawson** [comment]
> Which version, if any, should be used with the current SeaMonkey?

If you're going to use any, I guess the last (2.10.4) might work. But as I referenced above, there is also [Classic Password Editor](https://github.com/ddawson/Classic-Password-Editor). It's more up to date than SPE, albeit still years old. Do note, though, that I ended up dropping support for SeaMonkey due to some problem. Version 1.0.3 was the last that still supported it. I do not know how the compatibility is these days, as I have not developed these add-ons in years.
